// <auto-generated />
namespace AplombTech.WMS.CompanyDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WaterMeterAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WaterMeterAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201810011319531_WaterMeterAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
